### ISSUE TITLE
Add license information to the footer of each page

### ISSUE THREAD

**Issue by iq8al** [StudiMY/101-beginning-python#9]
At the footer of each page, we should add license information with a link, something like this:

> This Studi.my curriculum text is licensed under the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/).

**Comment by iq8al** [comment]
@cheeyim Do you think you can figure out how to do this? I think it has something to do with the templates.

**Comment by cheeyim** [comment]
@iq8al  - i think it's already inside the conf.py under source folder.

copyright = '2018, MARIMORE ENGINEERING SDN. BHD. (925539-H)'

**Comment by iqbalabd** [comment]
OK, I see them at the bottom. Thanks!
